name: Deploy to Cloudfront

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: us-east-2
  S3_BUCKET: amitb-s3-bucket

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.19.1
          cache: 'npm'
         # cache-dependency-path: subdir/package-lock.json
      - name: Install Angular
        run: |
          echo "$(ls -la)"
          npm install -g @angular/cli@8.19.3  
          sudo npm install -g yarn
          ng v

      - name: Install npm dependencies
        run: npm install --include=dev

      - name: Build preview library
        run: |
          npm run build:preview-library

      - name: Build application
        run: |
          npm run build:production
          echo "$(ls -la dist/)"
      
      - name: Build application
        run: echo "$(ls -la)" 

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: /*
          retention-days: 1

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [ build ]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Upload to S3
        run: aws s3 sync ./* s3://${{ env.S3_BUCKET }}/ --delete --acl public